# Generated by Django 2.1.7 on 2019-02-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmiforums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderator',
            old_name='usermane',
            new_name='username',
        ),
    ]
