# Generated by Django 2.1.7 on 2019-02-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmiforums', '0002_auto_20190221_0910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
