# Generated by Django 2.1.7 on 2019-02-21 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmiforums', '0003_auto_20190221_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 9, 55, 26, 52888), verbose_name='Created on'),
        ),
    ]
