# Generated by Django 2.1.7 on 2019-03-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmiforums', '0003_auto_20190321_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
