# Generated by Django 2.1.5 on 2019-04-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmiforums', '0005_auto_20190412_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
