# Generated by Django 2.1.7 on 2019-02-21 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jmiforums', '0005_auto_20190221_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 10, 4, 23, 182952, tzinfo=utc), verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 10, 4, 23, 181817, tzinfo=utc), verbose_name='Created on'),
        ),
    ]
