# Generated by Django 2.1.7 on 2019-02-21 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jmiforums', '0006_auto_20190221_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usermane',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='moderator',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 10, 5, 53, 909197, tzinfo=utc), verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 10, 5, 53, 909902, tzinfo=utc), verbose_name='Created on'),
        ),
    ]
