# Generated by Django 2.1.5 on 2019-04-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmiforums', '0006_remove_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subforum',
            name='subforum_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
