# Generated by Django 2.1.7 on 2019-02-21 11:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jmiforums', '0007_auto_20190221_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('subforum_id', models.IntegerField()),
                ('ques_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subforum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subforum_name', models.CharField(max_length=50)),
                ('ques_count', models.IntegerField()),
                ('arti_count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='moderator',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 11, 56, 49, 79603, tzinfo=utc), verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 11, 56, 49, 80660, tzinfo=utc), verbose_name='Created on'),
        ),
    ]
