# Generated by Django 2.1.7 on 2019-03-09 16:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jmiforums', '0008_auto_20190221_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 9, 16, 5, 45, 504461, tzinfo=utc), verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 9, 16, 5, 45, 505058, tzinfo=utc), verbose_name='Created on'),
        ),
    ]
