# Generated by Django 2.1.7 on 2019-03-10 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jmiforums', '0011_auto_20190309_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 10, 14, 18, 49, 831415, tzinfo=utc), verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 10, 14, 18, 49, 834405, tzinfo=utc), verbose_name='Created on'),
        ),
    ]
