# Generated by Django 2.1.7 on 2019-03-10 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jmiforums', '0012_auto_20190310_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='subforum',
            name='mod_id',
            field=models.ManyToManyField(blank=True, related_name='moderator', to='jmiforums.Moderator'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 10, 14, 26, 8, 700073, tzinfo=utc), verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='subforum_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 10, 14, 26, 8, 702336, tzinfo=utc), verbose_name='Created on'),
        ),
    ]
