# Generated by Django 2.1.7 on 2019-03-10 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jmiforums', '0013_auto_20190310_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 10, 14, 40, 41, 47328, tzinfo=utc), verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='subforum',
            name='ques_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 10, 14, 40, 41, 49620, tzinfo=utc), verbose_name='Created on'),
        ),
    ]
