# Generated by Django 2.1.7 on 2019-03-14 05:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jmiforums', '0014_auto_20190310_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='subforum',
            name='subforum_description',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 5, 40, 29, 544805, tzinfo=utc), verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 5, 40, 29, 547072, tzinfo=utc), verbose_name='Created on'),
        ),
    ]
